### PR TITLE
add support for @scoped/module-names

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/mafintosh/prebuild/issues/36

cc @corbinu

### CODE REVIEW

**Comment by mafintosh** [comment]
This would make @test/module and test-module clash though right?

**Comment by corbinu** [comment]
This looks good to me.

@mafintosh maybe a separate feature is in order to allow "prebuild_name" in the package.json which if present allows the normal package name to be overridden?

**Comment by ralphtheninja** [comment]
@mafintosh Aah yes it would. I'll update today.

**Comment by ralphtheninja** [comment]
I'll create a new PR based on top of https://github.com/mafintosh/prebuild/pull/39

**Pull request closed without merging**
