### PR TITLE
#50: Gyp refactor

### PR DESCRIPTION
**Pull request by brett19**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
LGTM!

**Comment by ralphtheninja** [comment]
@brett19 We should document `--compile=false` as well in the README and explain that the use case is for modules having .js fallbacks

**Comment by brett19** [comment]
P.S. Using -no-compile looks nicer :)

**Comment by ralphtheninja** [comment]
> P.S. Using -no-compile looks nicer :)

Agree!

**Comment by brett19** [comment]
@ralphtheninja Thanks for merging everything at once, I can stop the rebase/branch-management dance! :)

**Comment by ralphtheninja** [comment]
And I can prune your remote :D

**Comment by ralphtheninja** [comment]
2.6.0

Documented `--no-compile` flag [here](https://github.com/mafintosh/prebuild/commit/5737e33c8f387a9eb1b505b4107c3863c69e0c22)

**Pull request merged**
