### PR TITLE
Fixes #34: Use node-gyp 3.0.0 to install headers.

### LINKED ISSUE #34: Update node-gyp to 3.0
And use that to install headers as well.

### PR DESCRIPTION
**Pull request by brett19**
Also improved build rules to more similarily match the
way that node-gyp's cli invokes the node-gyp library and
improves logging when failures occur.

### CODE REVIEW

**Comment by brett19** [comment]
Do not merge.

**Comment by ralphtheninja** [comment]
:+1: Awesome!

**Comment by brett19** [comment]
Should be good to merge, appears to be working everywhere:
http://puu.sh/kkaVV.png

**Comment by ralphtheninja** [comment]
@brett19 You basically just did what I planned to do this week ;) I'll wait for @mafintosh to respond before merging.

@mafintosh Should this be a new patch?

**Comment by brett19** [comment]
@ralphtheninja I spent Friday afternoon and all day Monday trying to resolve various issues with prebuild running on my builders.  This ended up being by far the simplest way to fix it all in one swoop :)

**Comment by ralphtheninja** [comment]
@brett19 Aye, I think that's mainly due to `node-gyp` using smaller header tarballs when available.

**Comment by ralphtheninja** [comment]
@brett19 On a side note. Which windows targets are you building your modules on?

**Comment by brett19** [comment]
The matrix above is for VS2015.  Though I was using VS2012 and VS2013 before (it was just unnecessary, and had issues with Node.js 4.0.0's v8).

**Comment by mafintosh** [comment]
Great job everyone. @ralphtheninja yea we can patch release this

**Comment by mafintosh** [comment]
On a side note: I wonder if any of the remaining code inside prebuild now was written by me now hehe

**Comment by ralphtheninja** [comment]
@mafintosh lol well it's just code and it's still your idea, which is the important thing imo :)

**Comment by brett19** [comment]
@mafintosh Haha.  As an aside as well, we should probably consider having a small helper library which wraps the logic of invoking node-gyp with various parameters.  I might do that after this PR if it gets merged.

**Comment by ralphtheninja** [comment]
@brett19 I'm testing your branch on `leveldown` and I get some issues with `iojs@1.0.4`

prebuild-leveldown

**Comment by ralphtheninja** [comment]
@brett19 If you want to reproduce, clone leveldown and execute `prebuild` (obviously npm link your master first) inside `leveldown` folder

**Comment by brett19** [comment]
I've seen this before, its related to the `include/node/` vs `src/` thing.  getAbi has no check on retrying and retries indefinitely, I fixed it originally by introducing the switch between the two directories, but we should probably add a better check there so it doesnt loop out of control.  Can you paste me your `ls` of `$HOME/.node-gyp/`?

**Comment by ralphtheninja** [comment]
Downloading headers only using node-gyp seems to work fine:

node-gyp-install-1 0 4

**Comment by brett19** [comment]
I'll repro locally and resolve.  One moment :)

**Comment by ralphtheninja** [comment]
Aah. Missing `include` folder for that version?

**Comment by brett19** [comment]
I suspect the pathing might be different (ie: `include/iojs/` rather than `include/node`).

**Comment by ralphtheninja** [comment]
Hmm nope, it's something else. Here's my directory listing:

```
lms@ux301|16:35|~/.node-gyp $ tree -L 2 iojs-1.0.4/
iojs-1.0.4/
├── common.gypi
├── deps
│   ├── cares
│   ├── http_parser
│   ├── mdb_v8
│   ├── npm
│   ├── openssl
│   ├── uv
│   ├── v8
│   └── zlib
├── installVersion
├── src
│   ├── async-wrap.h
│   ├── async-wrap-inl.h
│   ├── base-object.h
│   ├── base-object-inl.h
│   ├── debug-agent.h
│   ├── env.h
│   ├── env-inl.h
│   ├── handle_wrap.h
│   ├── node_buffer.h
│   ├── node_constants.h
│   ├── node_counters.h
│   ├── node_crypto_bio.h
│   ├── node_crypto_clienthello.h
│   ├── node_crypto_clienthello-inl.h
│   ├── node_crypto_groups.h
│   ├── node_crypto.h
│   ├── node_dtrace.h
│   ├── node_file.h
│   ├── node.h
│   ├── node_http_parser.h
│   ├── node_i18n.h
│   ├── node_internals.h
│   ├── node_javascript.h
│   ├── node_object_wrap.h
│   ├── node_root_certs.h
│   ├── node_stat_watcher.h
│   ├── node_v8_platform.h
│   ├── node_version.h
│   ├── node_watchdog.h
│   ├── node_win32_etw_provider.h
│   ├── node_win32_etw_provider-inl.h
│   ├── node_win32_perfctr_provider.h
│   ├── node_wrap.h
│   ├── pipe_wrap.h
│   ├── queue.h
│   ├── req_wrap.h
│   ├── smalloc.h
│   ├── spawn_sync.h
│   ├── stream_wrap.h
│   ├── string_bytes.h
│   ├── tcp_wrap.h
│   ├── tls_wrap.h
│   ├── tree.h
│   ├── tty_wrap.h
│   ├── udp_wrap.h
│   ├── util.h
│   ├── util-inl.h
│   └── v8abbr.h
└── tools
    ├── msvs
    └── wrk
```

**Comment by ralphtheninja** [comment]
@brett19 Slightly off topic but since you mentioned getAbi. Maybe there is use for a separate module to extract the abi version which could be used for any target, e.g. `electron`

**Comment by brett19** [comment]
Resolved.  It was just getting confused by the iojs- prefix.

P.S. I am avoiding doing specific version validation, favouring path checking instead as it is more likely to hold up against weird version identifiers (like prerelease versions).

**Comment by ralphtheninja** [comment]
> P.S. I am avoiding doing specific version validation, favouring path checking instead as it is more likely to hold up against weird version identifiers (like prerelease versions).

+1

**Comment by ralphtheninja** [comment]
I can confirm all `leveldown` versions built successfully. Time to merge and release! :)

**Comment by ralphtheninja** [comment]
2.5.3

Thanks for awesome work @brett19 !

**Comment by brett19** [comment]
Don't release yet if you didn't already.

**Comment by brett19** [comment]
Looks like I was too late, but see: https://github.com/mafintosh/prebuild/pull/40

**Pull request merged**
