### PR TITLE
Make --download search local prebuilds folder first.

### PR DESCRIPTION
**Pull request by brett19**
This allows me to provide all the prebuilds on my build
server instead of having to rebuild the modules
when not neccessary.

### CODE REVIEW

**Comment by brett19** [comment]
Might be getting a little carried away on the releases :D

**Comment by brett19** [comment]
Oh fantastic, this change REALLY blew up the tests.

**Comment by brett19** [comment]
Interesting.  Just noticed `npm test` fails with any node version in the 4.x.y range.

**Comment by ralphtheninja** [comment]
@brett19 I think that's related to `a-native-module` that doesn't have any prebuilts for node 4.0.0 yet. (using that module for tests)

**Comment by ralphtheninja** [comment]
Just guessing now, might be unrelated :)

**Comment by brett19** [comment]
Yea, I just mentioned it, but didn't bother looking at why it was happening at all. :)

**Comment by brett19** [comment]
Any thoughts on this PR?  It helps slightly, but I'm worried it may cause some weird issue.  As an aside as well, I think we should make `--download` be `nolocal:true`, but also include a `--install` for use in `package.json>scripts>install` which searches locally as well.

**Comment by ralphtheninja** [comment]
I'm not sure of the use case here to be honest. You say you have a build server? Why can't you just put the binaries there and download from it?

**Comment by brett19** [comment]
Jenkins, and that makes it a pain in the butt to download from.  Could possibly work though, seems a little silly to do http download of a file that already exists in the directory tree though (under /prebuilds).

**Comment by ralphtheninja** [comment]
But if you have published the binaries, they will be downloaded from github and also cached locally in `~/.npm/_prebuilds`

**Comment by ralphtheninja** [comment]
On second thought. You obviously build the binaries on jenkins so it will be an unnecessary dowload from github the first time.

**Comment by brett19** [comment]
I also want to run the tests before I upload to GitHub.

**Comment by ralphtheninja** [comment]
@brett19 *nods* It's a good use case then imo :)

**Comment by brett19** [comment]
PR hell.  Can we merge these sometime soon :+1:

**Comment by brett19** [comment]
This should be good to merge I think?

**Pull request merged**
