### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by lgeiger**
Adresses https://github.com/mafintosh/prebuild/pull/137#issuecomment-263563172

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Ouch. New simple-get not playing nice with 0.12 and 0.10 :/

**Comment by juliangruber** [comment]
thanks!

**Comment by ralphtheninja** [comment]
Nice emojis! :)

**Comment by lgeiger** [comment]
> Nice emojis! :)

Stolen from [Atom's contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#git-commit-messages) 😇  😂

**Pull request merged**
