### PR TITLE
Correct all 'standard.js' failures and add it to test script.

### PR DESCRIPTION
**Pull request by brett19**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
I'm ok with this but lets hear what @mafintosh has to say. I guess this should be merged before the others.

**Comment by brett19** [comment]
I figured you were going to merge them all individually anyways considering you asked me to split them up for that reason >_<

**Comment by ralphtheninja** [comment]
I'll merge and update.

**Comment by ralphtheninja** [comment]
@brett19 Mind rebasing the other PRs onto latest master?

**Comment by brett19** [comment]
@mafintosh has standard on the node-gyp-install project and I don't usually follow the coding standard that is used on his projects, so it was useful.  Figured i'd bring it over here to prebuild :)

**Pull request merged**
