### PR TITLE
add --abi option

### PR DESCRIPTION
**Pull request by juliangruber**
My end goal is to have seamless electron integration, but for now this should enable a more manual process for downloading the desired prebuild

### CODE REVIEW

**Comment by mafintosh** [comment]
:+1: @ralphtheninja ?

**Comment by brett19** [comment]
I'm -1 to this change as it can cause confusion in non-electron cases.  Why not simply add a temporary --electron option for now?

**Comment by juliangruber** [comment]
@brett19 reaching `--electron` is the goal, i wrote this in the process of getting there and thought it would still be useful.

about non-electron cases, i think we just need to make clear which commands this option applies to.

**Comment by ralphtheninja** [comment]
@juliangruber if you want we could create a separate issue for this and spec out what we need, I can help out as well

**Comment by ralphtheninja** [comment]
Hmm @brett19 is on to something, but `--abi` is useful too.

As I see it, we want to

1. install prebuilt binaries from github, based on the abi version of electron, so we need the abi from somewhere, right?
2. if we can't find any prebuilt binaries, we want to call out to `node-gyp` (like we do now) but with some different settings, e.g. changing `HOME` and passing on `--dist-url`:

`HOME=~/.electron-gyp node-gyp rebuild --target=$TARGET --arch=$ARCH --dist-url=https://atom.io/download/atom-shell`

taken from [electron-demo](from here https://github.com/Level/electron-demo/blob/master/package.json#L9)

So first of all, to solve 1. we need the abi somehow and the question is how we get that. There are different methods for this, one being the one @juliangruber just mentioned [here](https://github.com/mafintosh/prebuild/issues/61#issuecomment-171641418), another being using either a hardcoded `--target=0.X.Y` or by using https://github.com/ralphtheninja/electron-version and using `node-gyp` to actually download the headers for electron with that target and using https://github.com/mafintosh/prebuild/blob/master/abi.js#L4 to just parse it out from the headers.

Did that make sense?

**Comment by ralphtheninja** [comment]
And btw, we can just use this PR to discuss the code and update. Once we're good, we just squash and clean up. Sound good?

**Comment by juliangruber** [comment]
working on the real `--electron` thing now

**Comment by juliangruber** [comment]
I've been working on a new module, https://github.com/juliangruber/require-recompile, that tackles this problem with a new approach: It patches `require()` so when you `require()` a module that has been built for a different version of node, it will recompile it. It will either call `node-gyp rebuild` or shell out the `prebuilt`, but for that `prebuilt` needs to support the `--abi` option.

So, can I get another +1 or a merge for this?

**Comment by brett19** [comment]
Hey Guys,
I guess what I'm confused about here is: does node-gyp support building for an ABI that is not the current one?  I was under the impression that it could not, but maybe it was added more recently or I was simply unaware.
Cheers, Brett

**Comment by juliangruber** [comment]
@brett19 yes it's possible: `node-gyp rebuild --target=X`

**Comment by ralphtheninja** [comment]
+1 You can just merge https://github.com/mafintosh/prebuild/pull/70 which will close this one

**Comment by juliangruber** [comment]
@ralphtheninja i'm just gonna merge this one since i suspect the require-recompile way will have way less edge cases than `--electron`, for example that it works on the whole dependency tree.

**Comment by ralphtheninja** [comment]
@juliangruber Are you fine using `github:mafintosh/prebuild` in `require-rebuild` for now?

**Comment by juliangruber** [comment]
yup no worries, it's still experimental

**Comment by ralphtheninja** [comment]
2.9.0

**Pull request merged**
