### PR TITLE
util.readGypFile takes opts parameter

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@hintjens Mind testing out this branch?

**Comment by ralphtheninja** [comment]
@hintjens On a side note, would you mind being a contributor to prebuild?

**Comment by hintjens** [comment]
@ralphtheninja I've been using it a few times and it works nicely. Thanks for the cleanups.

And I'd love to be regarded as a contributor to prebuild, yes :) Thank you. One warning: I've been known to promote a process called [C4](http://rfc.zeromq.org/spec:22), which encourages fast merges and post-merge fixups and discussion, to remove the usual blocking waits we see on PRs. You're already doing this (and that's wonderful).

Thanks for prebuild btw, it is the top piece of a complex puzzle we've been solving to get ZeroMQ libraries shipping nicely into the node.js world.

**Comment by ralphtheninja** [comment]
> And I'd love to be regarded as a contributor to prebuild, yes :) Thank you. One warning: I've been known to promote a process called C4, which encourages fast merges and post-merge fixups and discussion, to remove the usual blocking waits we see on PRs. You're already doing this (and that's wonderful).

This is my style too :)

@mafintosh Added you as contributor to this repo. I'll update package.json as well.

**Comment by ralphtheninja** [comment]
> Thanks for prebuild btw, it is the top piece of a complex puzzle we've been solving to get ZeroMQ libraries shipping nicely into the node.js world.

Pretty funny that I bought your book at FOSDEM and once I traveled back to Sweden, you show up here :)

**Comment by hintjens** [comment]
So thank you for adding me as contributor :)

Can I propose we document a simple contribution process, e.g.:

- no commits direct to master
- all commits as pull requests (one or several per PR)
- each commit solves one identifiable problem
- never merge one's own PRs, another contributor does this

(This is a distillation of C4, which I warned you about :)

**Comment by hintjens** [comment]
:-) thank you for helping to pay for my kids' university...

**Comment by mafintosh** [comment]
i'm fine with those guidelines. should we put them in CONTRIBUTING.md?

**Comment by mafintosh** [comment]
welcome on board @hintjens

**Comment by hintjens** [comment]
@mafintosh ok, done: #96

**Comment by ralphtheninja** [comment]
> never merge one's own PRs, another contributor does this

So then you can start by merging mine :)

**Comment by ralphtheninja** [comment]
4.0.0

**Pull request merged**
