### PR TITLE
Bump node versions and add node 7.0.0

### PR DESCRIPTION
**Pull request by lgeiger**
So `prebuilt --all` will build for Node.js 7 as well.

### CODE REVIEW

**Comment by lgeiger** [comment]
@ralphtheninja It looks like https://github.com/ralphtheninja/a-native-module needs to be updated in order to run the test suite on Node 7.

**Comment by ralphtheninja** [comment]
@lgeiger I'll get on that today!

**Comment by ralphtheninja** [comment]
4.4.0

I'll work on the tests once leveldown prebuilts have been made.

@lgeiger thanks!

**Comment by ralphtheninja** [comment]
@lgeiger Aaah you're using prebuild for zmq? :heart:

**Comment by lgeiger** [comment]
Yes we just moved our [repo](https://github.com/zeromq/zeromq.js) into the zeromq org.

It's working really great end to end with Travis and AppVeyor! Thanks a lot for this awesome package.

The only downside is that we still have to build from source if we want to use it inside with electron.

**Comment by ralphtheninja** [comment]
Nice! So happy that this module can contribute to the zmq community. Building for electron is still an enigma for me.

**Comment by rgbkrk** [comment]
Yeah it's ok though. Our fallback with Electron is so clean now that I'm pleased. I'm even happier that we made zeromq easier to install for node users in general. 😄

**Pull request merged**
