### PR TITLE
Problem: Failed to locate `node.h` and `node_version.h`

### PR DESCRIPTION
**Pull request by hintjens**
Hits when installing new ABI versions. Cause was gypinstall.js not
passing the backend down to gyp, so headers were installed into
$HOME/.node-gyp when using the --backend=node-ninja.

Solution: gypinstall.js passes opts.backend down when calling backend.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Apart from `standard`. LGTM.

**Comment by hintjens** [comment]
OK, fixed those two issues. Thanks for the pointers.

**Comment by ralphtheninja** [comment]
:+1:

**Comment by ralphtheninja** [comment]
4.0.2

**Pull request merged**
