### PR TITLE
remove 0.10, it's dead

### PR DESCRIPTION
**Pull request by ralphtheninja**
The other updates aren't really necessary since it's the major we care about (the abi has changed) but just syncing with what's out there at this point in time

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@juliangruber I want to release https://github.com/mafintosh/prebuild/pull/135 today. Can we merge this as well?

**Comment by juliangruber** [comment]
+1 from me, however this is a breaking change so maybe a +1 from @mafintosh would be great as well

**Comment by ralphtheninja** [comment]
Agree. Well then I can leave it for now and release 4.5.0.

**Comment by mafintosh** [comment]
I'd like to keep this in there as long as 0.10 is default on debian

**Pull request closed without merging**
