### PR TITLE
Bump node-abi@2.0.0

### PR DESCRIPTION
**Pull request by lgeiger**
This adds Electron 1.5 and 1.6 to supported Targets

### CODE REVIEW

**Comment by lgeiger** [comment]
@juliangruber @mafintosh @ralphtheninja It would be great if we could release this and https://github.com/mafintosh/prebuild-install/pull/31.

We would like to ship a new version of [zeromq.js](https://github.com/zeromq/zeromq.js) with support for Electron 1.6.

**Comment by ralphtheninja** [comment]
LGTM

**Comment by ralphtheninja** [comment]
New patch?

**Comment by lgeiger** [comment]
I think minor would be better since `prebuild --all` now also builds for Electron 1.5 and 1.6.

**Comment by ralphtheninja** [comment]
check

**Comment by ralphtheninja** [comment]
6.1.0

**Comment by lgeiger** [comment]
Thanks!

**Comment by lgeiger** [comment]
@ralphtheninja Whoops it's only published on GitHub. On [npm](https://www.npmjs.com/package/prebuild) there's  still v6.0.2.

I would publish it but I don't have access there.

**Comment by ralphtheninja** [comment]
@lgeiger Gah, sorry. Done.

**Comment by lgeiger** [comment]
No problem, thanks for the work!

**Pull request merged**
