### PR TITLE
Multiple issue fixes

### PR DESCRIPTION
**Pull request by brett19**

### CODE REVIEW

**Comment by brett19** [comment]
PR hell. Can we merge these sometime soon :+1:

**Comment by brett19** [comment]
They've deprecated fs.exists in place of fs.access.  Made kind of a mess in the tests because of the switch depending on that.

**Comment by ralphtheninja** [comment]
Sorry to be a pain and I know you want to fix things quick, but would you mind breaking down this into two separate PRs? It's easier to reason about what has changed.

**Comment by brett19** [comment]
Hey @ralphtheninja,
They are a single PR due to dependance and having them as separate PRs was making it a challenge to correct issues without making rebase issues.  Not because I was trying to move quickly.  I'll try to split it later tonight when I'm around my computer again.
Cheers, Brett

**Comment by ralphtheninja** [comment]
@brett19 Awesome! We'll merge them *all*. Don't worry ;)

**Comment by brett19** [comment]
Note: prebuild does not currently pass the latest standards.  Going to correct all of that in a later commit.

**Comment by brett19** [comment]
Well that was fun.  I split them all up for easier review.

**Pull request closed without merging**
