### PR TITLE
breaking: use .prebuild for prebuild versions

### PR DESCRIPTION
**Pull request by juliangruber**
rename the build portion of `--target` to `--prebuild`, so it still looks nice in the prebuildrc.

tests are passing now, i hope though i didn't miss anything.

what do you devs think?

### CODE REVIEW

**Comment by juliangruber** [comment]
fixes #80

**Comment by ralphtheninja** [comment]
I'm +1. Maybe rename `targets.js` to something better? Or maybe replace:

```js
if (rc.all === true) {
  delete rc.prebuild
  rc.prebuild = targets
}
```

with 

```js
if (rc.all === true) {
  rc.prebuild = [
    '0.10.41',
    '0.12.9',
    '1.0.4',
    '1.8.4',
    '2.5.0',
    '3.3.1',
    '4.2.4',
    '5.3.0'
  ]
}
```

and remove `targets.js` completely?

**Comment by juliangruber** [comment]
targets.js is used in tests as well, so i guess we need to keep it

**Comment by ralphtheninja** [comment]
> targets.js is used in tests as well, so i guess we need to keep it

I trust your judgment :grinning: 

@mafintosh Anything to add?

**Comment by mafintosh** [comment]
@juliangruber @ralphtheninja i trust your judgement :tada:

**Comment by juliangruber** [comment]
i'll look over this for a bit and then merge :)

**Comment by juliangruber** [comment]
needed to update docs. looks good? i'll squash once we agree to merge

**Comment by ralphtheninja** [comment]
> needed to update docs. looks good? i'll squash once we agree to merge

Looks good!

**Comment by juliangruber** [comment]
@mafintosh @ralphtheninja ready to publish a 3.0.0?

**Comment by ralphtheninja** [comment]
:ship:

**Comment by juliangruber** [comment]
3.0.0 it is :rocket:

**Comment by juliangruber** [comment]
https://twitter.com/juliangruber/status/697867311554936833

**Comment by ralphtheninja** [comment]
:fireworks:

**Pull request merged**
