### PR TITLE
audit code with nsp check

### PR DESCRIPTION
**Pull request by ralphtheninja**
nsp-check

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Tests should fail du to `hawk` dependency of `request`

**Comment by ralphtheninja** [comment]
Fix for it here https://github.com/request/request/pull/2026

**Comment by juliangruber** [comment]
+1 to merge once passing

**Comment by ralphtheninja** [comment]
Should be good to merge, because apparently it was fixed in `hawk@3.1.3` as well, see https://github.com/request/request/pull/1891#issuecomment-173671203

**Comment by juliangruber** [comment]
re running the build...

**Comment by juliangruber** [comment]
nsp is still complaining, says we need hawk >= 4.1.1

**Comment by ralphtheninja** [comment]
Yeah, well nsp is wrong

**Comment by ralphtheninja** [comment]
We should tell nsp about this so they know about hawk 3.1.3

**Comment by ralphtheninja** [comment]
There we go.

**Comment by ralphtheninja** [comment]
2.9.0

**Pull request merged**
