### PR TITLE
enable building with --debug

### PR DESCRIPTION
**Pull request by ralphtheninja**
* make sure prebuild catches --debug from npm environment (npm i --debug)
* if --debug is set, build to build/Debug (util.releaseFolder()) + tests
* pass in --debug to node-gyp if set
* factor out gyp code + tests

Closes https://github.com/mafintosh/prebuild/issues/29

### CODE REVIEW

**Comment by mafintosh** [comment]
:+1:

**Comment by ralphtheninja** [comment]
New patch or new minor? Technically we were using `--debug` before this but only for the download url.

**Comment by mafintosh** [comment]
Minor

**Comment by ralphtheninja** [comment]
2.5.0

**Pull request merged**
