### PR TITLE
A few minor additions to help productivity.

### PR DESCRIPTION
**Pull request by brett19**

### CODE REVIEW

**Comment by brett19** [comment]
Any thoughts on this guys?

**Comment by ralphtheninja** [comment]
I'm +1 on `--install`

Maybe tweak the `upload` thing to *always* try to upload everything from `prebuilds/` folder? I.e. remove the extra argument and always have `--upload` work that way.

@mafintosh Any thoughts?

**Comment by mafintosh** [comment]
+1 on `--install` as well

**Comment by ralphtheninja** [comment]
@brett19 I think you should make a separate PR for just the `--install` change so we can merge and release that today and discuss the other in a separate PR.

**Comment by brett19** [comment]
Uhhh... Deleted master?  Oops....

**Comment by ralphtheninja** [comment]
Hehe

**Comment by brett19** [comment]
Fixed: 
https://github.com/mafintosh/prebuild/pull/63

**Pull request closed without merging**
