### PR TITLE
build all targets with --all

### PR DESCRIPTION
**Pull request by ralphtheninja**
@mafintosh Do you think we should really support node 0.8 as well? It definitely doesn't build for `leveldown`. Not exactly sure why, but I suspect that `nan` doesn't support it.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@mafintosh Hmm, why isn't travis building?

**Comment by mafintosh** [comment]
@ralphtheninja i'm fine with excluding 0.8 from --all

**Comment by mafintosh** [comment]
looking good otherwise

**Comment by ralphtheninja** [comment]
> @ralphtheninja i'm fine with excluding 0.8 from --all

Cool. I'll clean up PR and merge.

**Comment by ralphtheninja** [comment]
2.7.0

**Pull request merged**
